before_script: ./test/create_mock_dbs.sh
language: node_js
dist: bionic
node_js:
    - "12"
    - "11"
    - "10"
    - "9"
    - "8"
services: mysql
test:
    adapter: mysql2
    database: mock_db
    username: travis
    encoding: utf8
